### ISSUE TITLE
Adopting Standard Practice: Adding Newline at End of File

### ISSUE THREAD

**Issue by UsadaPeko** [Team-Ampersand/Dotori-server-V2#268]
안녕하세요, 귀여운 우사다입니다.
코드를 살펴보다가 발견한 이슈가 있어서 제보드립니다.

linux 환경에서 text file의 마지막줄에 new line이 있는 것은 꽤나 많이 받아들여지고 권장되는 관례입니다.
PR들을 읽다가 일부 파일들에서 마지막 줄에 new line이 없어서 별도의 표시가 나는 항목들을 발견했습니다.
아래에 예시 이미지를 첨부해봅니다.

<img width="600" alt="sample" src="https://github.com/Team-Ampersand/Dotori-server-V2/assets/93421000/9df985f1-43e7-44e9-a80f-914193fbc2b7">

이러한 것들이 심각하지는 않지만 지키면 좋을 것 같은 프랙티스라서 이슈 남겨봅니다.
선배님들 너무 멋지십니다!!

ref: https://www.baeldung.com/linux/files-end-with-newlines

**Comment by UsadaPeko** [comment]
이 동아리 들어가고싶네여...ㅋㅋ

**Comment by UsadaPeko** [comment]
@esperar 요거 한번만 검토해주세영! 괜찮은걸로 결정되면 제가 기여해볼게여ㅋㅋㅋ

**Comment by esperar** [comment]
안녕하세요. 저희 &mersand 프로젝트에 관심을 가져주셔서 감사합니다.

해당하신 사항을 검토해봤는데, 관례를 지키는 것은 협업 관점에서도 좋은 지적인 것 같습니다.
그러나 자바 텍스트 파일에서 빌드하는 과정에서는 마지막 엔터의 여부로 예기치않은 오류는 발생하지 않습니다. 
이는 자바 컴파일러는 자바 텍스트 코드 파일 맨 하단에 엔터가 존재하지 않아도 처리할 수 있기 때문입니다.
그렇기에 해당사항의 이슈는 그렇게 심각한 문제는 아닌 것 같습니다.  
그리고 모든 코드파일의 하단부에 엔터를 추가하기에는 어려움이 있을 수 있습니다.

코드스타일이나 관례의 관점으로는 좋은 지적인 것 같습니다.
만약 기여하고싶으시다면 말리지는 않겠지만 괜히 수고를 할 필요는 없어보입니다. 시간은 소중하니까요

**Comment by esperar** [comment]
> @esperar 요거 한번만 검토해주세영! 괜찮은걸로 결정되면 제가 기여해볼게여ㅋㅋㅋ

안녕하세요. 저희 &mersand 프로젝트에 관심을 가져주셔서 감사합니다.

해당하신 사항을 검토해봤는데, 관례를 지키는 것은 협업 관점에서도 좋은 지적인 것 같습니다.
그러나 자바 텍스트 파일에서 빌드하는 과정에서는 마지막 엔터의 여부로 예기치않은 오류는 발생하지 않습니다.
이는 자바 컴파일러는 자바 텍스트 코드 파일 맨 하단에 엔터가 존재하지 않아도 처리할 수 있기 때문입니다.
그렇기에 해당사항의 이슈는 그렇게 심각한 문제는 아닌 것 같습니다.
그리고 모든 코드파일의 하단부에 엔터를 추가하기에는 어려움이 있을 수 있습니다.

코드스타일이나 관례의 관점으로는 좋은 지적인 것 같습니다.
만약 기여하고싶으시다면 말리지는 않겠지만 괜히 수고를 할 필요는 없어보입니다. 시간은 소중하니까요
